services:
  mysql:
    image: mysql:8.0
    container_name: mysql-gambarmonologi
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pengumuman_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma-gambarmonologi
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root

  backend:
    build:
      context: ./backend-gambarmonologi2
      dockerfile: Dockerfile
    container_name: backend-gambarmonologi
    restart: always
    depends_on:
      - mysql
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: pengumuman_db
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - ./backend-gambarmonologi2:/var/www/html
      - ./asset-gambarmonologi/images:/var/www/html/storage/app/public/images
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

volumes:
  mysql_data: